package com.cube.fusion.core.processor

/**
 * Interface used to define a single step that can pre-process a piece of Fusion data by transforming it before it is used to populate UI
 *
 * Created by JR Mitchell on 28/April/2023.
 * Copyright ® 3SidedCube. All rights reserved.
 *
 * @param T The type of the data that this pre-processes
 */
fun interface FusionDataPreprocessor <T> {
	/**
	 * Pre-processes the supplied [data], transforming it into a new instance of [T]
	 *
	 * @param data The data to process
	 * @return A new instance of [T] generated by applying the pre-processing to [data]
	 */
	fun preprocess(data: T): T
}
